swagger: '2.1'
info:
  title: sample crudl API
  description: Sample crudl users API
  version: 1.0.0
consumes:
  - application/json
produces:
  - application/json
basePath: /api
components:
  parameters:
    id:
      in: path
      name: id
      required: true
      schema:
        type: string
      description: user id
    user:
      in: body
      name: user
      required: true
      schema:
        type: object
      description: user object
    username:
      in: body
      name: username
      required: true
      schema:
        type: string
      description: username

paths:
  /users:
    get:
      summary: users
      description: get a list of all of the users from the DB
      operationId: getUsers
      tags:
        - Users
      responses:
        '200':
          description: OK
          schema:
            type: array
            example: [
              {
              "location": {
              "street": "1097 the avenue",
              "city": "Newbridge",
              "state": "ohio",
              "zip": "28782"
              },
              "name": {
              "title": "miss",
              "first": "alison",
              "last": "reid"
              },
              "picture": {
              "large": "https://randomuser.me/api/portraits/women/60.jpg",
              "medium": "https://randomuser.me/api/portraits/med/women/60.jpg",
              "thumbnail": "https://randomuser.me/api/portraits/thumb/women/60.jpg"
              },
              "registered": "1970-01-15T07:39:36.893Z",
              "_id": "5abe62dd0e32003dc69ed9d7",
              "gender": "female",
              "email": "alison.reid@example.com",
              "username": "tinywolf709",
              "password": "rockon",
              "salt": "lypI10wj",
              "md5": "bbdd6140e188e3bf68ae7ae67345df65",
              "sha1": "4572d25c99aa65bbf0368168f65d9770b7cacfe6",
              "sha256": "ec0705aec7393e2269d4593f248e649400d4879b2209f11bb2e012628115a4eb",
              "dob": "1970-01-11T19:07:51.968Z",
              "phone": "031-541-9181",
              "cell": "081-647-4650",
              "PPS": "3302243T",
              "__v": 0
              }
            ]
    post:
      summary: Create a user
      description: create new user
      operationId: createUser
      tags:
        - Users
      parameters:
        - $ref: '#/components/parameters/user'
      responses:
        '201':
          description: OK
          schema:
            type: object
            properties:
              _id:
                type: string
                example: fe9593f590c180f972d1a9f2a29c49b76c0c61c83919fe362b53abb976f5a94a
              location:
                type: object
                example: {
                  "street": "1097 the avenue",
                  "city": "Newbridge",
                  "state": "ohio",
                  "zip": "28782"
                }
              name:
                type: object
                example: {
                  "title": "miss",
                  "first": "alison",
                  "last": "reid"
                }
              picture:
                type: object
                example: {
                  "large": "https://randomuser.me/api/portraits/women/60.jpg",
                  "medium": "https://randomuser.me/api/portraits/med/women/60.jpg",
                  "thumbnail": "https://randomuser.me/api/portraits/thumb/women/60.jpg"
                }
              registered:
                type: string
                example: 1970-01-15T07:39:36.893Z
              gender:
                type: string
                example: "female"
              email:
                type: string
                example: "alison.reid@example.com"
              username:
                type: string
                example: "tinywolf709"
              password:
                type: string
                example: "rockon"
              salt:
                type: string
                example: "lypI10wj"
              md5:
                type: string
                example: "bbdd6140e188e3bf68ae7ae67345df65"
              sha1:
                type: string
                example: "4572d25c99aa65bbf0368168f65d9770b7cacfe6"
              sha256:
                type: string
                example: "ec0705aec7393e2269d4593f248e649400d4879b2209f11bb2e012628115a4eb"
              dob:
                type: string
                example: "1970-01-11T19:07:51.968Z"
              phone:
                type: string
                example: "031-541-9181"
              cell:
                type: string
                example: "081-647-4650"
              PPS:
                type: string
                example: "3302243T"
        '403':
          description: Unable to create new user
          schema:
            type: object
            properties:
              error:
                type: string
                example: Unable to create new user
    delete:
      summary: delete all users
      description: delete all of the users from the DB
      operationId: deleteUsers
      tags:
        - Users
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
                example: All users deleted successfully
  /users/{id}:
    put:
      summary: Update a user
      description: update an existing user
      operationId: updateUser
      tags:
        - Users
      parameters:
        - $ref: '#/components/parameters/username'
      responses:
        '201':
          description: OK
          schema:
            type: object
            properties:
              _id:
                type: string
                example: fe9593f590c180f972d1a9f2a29c49b76c0c61c83919fe362b53abb976f5a94a
              location:
                type: object
                example: {
                  "street": "1097 the avenue",
                  "city": "Newbridge",
                  "state": "ohio",
                  "zip": "28782"
                }
              name:
                type: object
                example: {
                  "title": "miss",
                  "first": "alison",
                  "last": "reid"
                }
              picture:
                type: object
                example: {
                  "large": "https://randomuser.me/api/portraits/women/60.jpg",
                  "medium": "https://randomuser.me/api/portraits/med/women/60.jpg",
                  "thumbnail": "https://randomuser.me/api/portraits/thumb/women/60.jpg"
                }
              registered:
                type: string
                example: 1970-01-15T07:39:36.893Z
              gender:
                type: string
                example: "female"
              email:
                type: string
                example: "alison.reid@example.com"
              username:
                type: string
                example: "tinywolf709"
              password:
                type: string
                example: "rockon"
              salt:
                type: string
                example: "lypI10wj"
              md5:
                type: string
                example: "bbdd6140e188e3bf68ae7ae67345df65"
              sha1:
                type: string
                example: "4572d25c99aa65bbf0368168f65d9770b7cacfe6"
              sha256:
                type: string
                example: "ec0705aec7393e2269d4593f248e649400d4879b2209f11bb2e012628115a4eb"
              dob:
                type: string
                example: "1970-01-11T19:07:51.968Z"
              phone:
                type: string
                example: "031-541-9181"
              cell:
                type: string
                example: "081-647-4650"
              PPS:
                type: string
                example: "3302243T"
        '403':
          description: Unable to update user
          schema:
            type: object
            properties:
              error:
                type: string
                example: Unable to update user
    get:
      summary: List all users.
      description:  Lists all of the users
      operationId: getUser
      parameters:
        - $ref: '#/components/parameters/id'
      tags:
        - Users
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              _id:
                type: string
                example: fe9593f590c180f972d1a9f2a29c49b76c0c61c83919fe362b53abb976f5a94a
              location:
                type: object
                example: {
                  "street": "1097 the avenue",
                  "city": "Newbridge",
                  "state": "ohio",
                  "zip": "28782"
                }
              name:
                type: object
                example: {
                  "title": "miss",
                  "first": "alison",
                  "last": "reid"
                }
              picture:
                type: object
                example: {
                  "large": "https://randomuser.me/api/portraits/women/60.jpg",
                  "medium": "https://randomuser.me/api/portraits/med/women/60.jpg",
                  "thumbnail": "https://randomuser.me/api/portraits/thumb/women/60.jpg"
                }
              registered:
                type: string
                example: 1970-01-15T07:39:36.893Z
              gender:
                type: string
                example: "female"
              email:
                type: string
                example: "alison.reid@example.com"
              username:
                type: string
                example: "tinywolf709"
              password:
                type: string
                example: "rockon"
              salt:
                type: string
                example: "lypI10wj"
              md5:
                type: string
                example: "bbdd6140e188e3bf68ae7ae67345df65"
              sha1:
                type: string
                example: "4572d25c99aa65bbf0368168f65d9770b7cacfe6"
              sha256:
                type: string
                example: "ec0705aec7393e2269d4593f248e649400d4879b2209f11bb2e012628115a4eb"
              dob:
                type: string
                example: "1970-01-11T19:07:51.968Z"
              phone:
                type: string
                example: "031-541-9181"
              cell:
                type: string
                example: "081-647-4650"
              PPS:
                type: string
                example: "3302243T"
    delete:
      summary: delete a user
      description: delete a user from the DB
      operationId: deleteUser
      parameters:
        - $ref: '#/components/parameters/id'
      tags:
        - Users
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
                example: "User deleted successfully: 5abe62dd0e32003dc69ed9d7"

